Repository mozilla/burnham, pull requests merged in 2020-10, with the labels that each got.

#81 Update labels file 📝
  labels.toml
Labels: GitHub, project

#78 Initial commit adding dependabot.
  application/Dockerfile
  application/requirements.txt
  dependabot.yml
Labels: Dependabot, dependencies, docker

#82 Update documentation 📝
  README.md
  application/README.md
  bigquery/README.md
Labels: docs

#91 Revert "Bump glean-parser from 1.28.6 to 1.29.0 in /application" 📦
  application/requirements.txt
Labels: dependencies

#92 Set up GitHub code owners 📋
  .github/CODEOWNERS
Labels: GitHub, project

#95 Set up code coverage report 🤖
  application/pyproject.toml
  application/tox.ini
Labels: CircleCI, code quality

#98 Increase test coverage for burnham 🤖
  application/pyproject.toml
  application/src/burnham/experiments.py
  application/tests/conftest.py
  application/tests/test_burnham.py
  application/tests/test_cli.py
  application/tests/test_experiments.py
  application/tests/test_missions.py
Labels: application, code quality
